<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FaturamentoNfHeader extends Model
{
    use HasFactory;

    protected $primaryKey = 'nfhdr_id';
    
    protected $fillable = [
        'nfhdr_emp',
        'nfhdr_num',
        'nfhdr_sts',
        'nfhdr_tip_reg',
        'nfhdr_num_ped',
        'nfhdr_num_nf',
        'nfhdr_ser_nf',
        'nfhdr_dt_nf',
        'nfhdr_hr_nf',
        'nfhdr_cfop',
        'nfhdr_cme',
        'nfhdr_dt_ped',
        'nfhdr_dt_fec_ped',
        'nfhdr_usu',
        'nfhdr_ori',
        'nfhdr_tor',
        'nfhdr_cli',
        'nfhdr_cpg',
        'nfhdr_vlr_itm_pro',
        'nfhdr_vlr_itm_s_dsc',
        'nfhdr_vlr_itm_c_dsc',
        'nfhdr_vlr_mrc',
        'nfhdr_vlr_alq_dsc_mrc',
        'nfhdr_vlr_dsc_mrc',
        'nfhdr_vlr_srv',
        'nfhdr_vlr_srv_ter',
        'nfhdr_vlr_alq_dsc_srv',
        'nfhdr_vlr_dsc_srv',
        'nfhdr_vlr_dac',
        'nfhdr_vlr_lqm',
        'nfhdr_vlr_lqs',
        'nfhdr_vlr_sbt',
        'nfhdr_vlr_ipi',
        'nfhdr_vlr_tot_nf',
        'nfhdr_vlr_bc_icms',
        'nfhdr_vlr_alq_icms',
        'nfhdr_vlr_icms',
        'nfhdr_qtd_ppg',
        'nfhdr_vlr_ent',
        'nfhdr_nfb',
        'nfhdr_sfb',
        'nfhdr_dfb',
        'nfhdr_vlr_alq_ir',
        'nfhdr_vlr_ir',
        'nfhdr_vlr_arr',
        'nfhdr_orc',
        'nfhdr_nec',
        'nfhdr_rnu',
        'nfhdr_rse',
        'nfhdr_vlr_pis_ret',
        'nfhdr_vlr_cof_ret',
        'nfhdr_vlr_csl_ret',
        'nfhdr_vlr_ir_ret',
        'nfhdr_vlr_inss_ret',
        'nfhdr_vlr_bc_pis',
        'nfhdr_vlr_alq_pis',
        'nfhdr_vlr_pis',
        'nfhdr_vlr_bc_cof',
        'nfhdr_vlr_alq_cof',
        'nfhdr_vlr_cof',
        'nfhdr_vlr_bc_pis_dac',
        'nfhdr_vlr_alq_pis_dac',
        'nfhdr_vlr_pis_dac',
        'nfhdr_vlr_bc_cof_dac',
        'nfhdr_vlr_alq_cof_dac',
        'nfhdr_vlr_cof_dac',
        'nfhdr_vlr_alq_aic_dac',
        'nfhdr_cal_rat_dac',
        'nfhdr_vlr_fcp_uf_dest',
        'nfhdr_vlr_icms_uf_dest',
        'nfhdr_vlr_icms_uf_remet',
        'nfhdr_pres_comp',
        'nfhdr_vlr_fcp',
        'nfhdr_vlr_fcp_st',
        'nfhdr_uf_saida_pais',
        'nfhdr_loc_exporta',
        'nfhdr_loc_despacho',
        'nfhdr_ind_con_final',
        'nfhdr_vlr_icms_deson'
    ];
}
